/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContribuerRouteImport } from './routes/contribuer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as InterviewsIndexRouteImport } from './routes/interviews/index'
import { Route as ReportsIdRouteImport } from './routes/reports/$id'
import { Route as InterviewsIdRouteImport } from './routes/interviews/$id'
import { Route as ReportsKindIdRouteImport } from './routes/reports/$kind/$id'

const ContribuerRoute = ContribuerRouteImport.update({
  id: '/contribuer',
  path: '/contribuer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIndexRoute = InterviewsIndexRouteImport.update({
  id: '/interviews/',
  path: '/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/interviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsKindIdRoute = ReportsKindIdRouteImport.update({
  id: '/reports/$kind/$id',
  path: '/reports/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/contribuer': typeof ContribuerRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/$kind/$id': typeof ReportsKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/contribuer': typeof ContribuerRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/interviews': typeof InterviewsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/$kind/$id': typeof ReportsKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/contribuer': typeof ContribuerRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/interviews/': typeof InterviewsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/$kind/$id': typeof ReportsKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carte'
    | '/contact'
    | '/contribuer'
    | '/interviews/$id'
    | '/reports/$id'
    | '/interviews/'
    | '/reports/'
    | '/reports/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carte'
    | '/contact'
    | '/contribuer'
    | '/interviews/$id'
    | '/reports/$id'
    | '/interviews'
    | '/reports'
    | '/reports/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/carte'
    | '/contact'
    | '/contribuer'
    | '/interviews/$id'
    | '/reports/$id'
    | '/interviews/'
    | '/reports/'
    | '/reports/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteRoute: typeof CarteRoute
  ContactRoute: typeof ContactRoute
  ContribuerRoute: typeof ContribuerRoute
  InterviewsIdRoute: typeof InterviewsIdRoute
  ReportsIdRoute: typeof ReportsIdRoute
  InterviewsIndexRoute: typeof InterviewsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsKindIdRoute: typeof ReportsKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contribuer': {
      id: '/contribuer'
      path: '/contribuer'
      fullPath: '/contribuer'
      preLoaderRoute: typeof ContribuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/': {
      id: '/interviews/'
      path: '/interviews'
      fullPath: '/interviews/'
      preLoaderRoute: typeof InterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/interviews/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$kind/$id': {
      id: '/reports/$kind/$id'
      path: '/reports/$kind/$id'
      fullPath: '/reports/$kind/$id'
      preLoaderRoute: typeof ReportsKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteRoute: CarteRoute,
  ContactRoute: ContactRoute,
  ContribuerRoute: ContribuerRoute,
  InterviewsIdRoute: InterviewsIdRoute,
  ReportsIdRoute: ReportsIdRoute,
  InterviewsIndexRoute: InterviewsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsKindIdRoute: ReportsKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
